POST https://student-register-bnaf.onrender.com/create
Content-type: application/json

{
    "nm_login":"bru",
    "cd_senha":"asd",
    "cd_curso": "858cfd10-16fa-45a0-b23b-59534450f7e2"
}

###

POST https://student-register-bnaf.onrender.com/login
Content-type: application/json

{
    "nm_login": "",
    "cd_senha": ""
}

###

GET https://student-register-bnaf.onrender.com/sessionCheck
token: a9ebb5f9-d1be-404c-818f-b51e97e67b19

###

GET https://student-register-bnaf.onrender.com/loginList?search=&curso=

###

PUT https://student-register-bnaf.onrender.com/login/
Content-type: application/json

{
    "nm_login":""
}

###

DELETE https://student-register-bnaf.onrender.com/login/