POST http://localhost:3333/turno
Content-Type: application/json

{
    "cd_curso": "",
    "nm_turno": ""
}

###

GET http://localhost:3333/turno?search=&curso=

###

PUT http://localhost:3333/turno/
Content-Type: application/json

{
    "cd_curso": "",
    "nm_turno": ""
}

###

DELETE http://localhost:3333/turno/