POST http://localhost:3333/estagiario
Content-Type: application/json

{
    "cd_curso":"", 
    "cd_registroMatricula":"", 
    "nm_statusMatricula":"",
    "nm_turno":"",
    "nm_ciclo":"",
    "dt_inicioEstagio":"",
    "qt_horaEstagioEntrada":"",
    "qt_horasEstagio":"",
    "cd_empresa":"",
    "ic_check": ,
    "dt_periodoComeco":"", 
    "dt_periodoTermino":"",
    "nm_estagiario":""
}

###

GET http://localhost:3333/estagiario?search=&empresa=&RA=&curso=&statusMatricula=&check=

###

PUT http://localhost:3333/estagiario/206378
Content-Type: application/json

{
    "cd_curso":"", 
    "dt_periodoComeco":"", 
    "dt_periodoTermino":"", 
    "cd_empresa":"", 
    "nm_estagiario":"",
    "nm_statusMatricula":"",
    "nm_turno":"",
    "nm_ciclo":"",
    "dt_inicioEstagio":"",
    "qt_horaEstagioEntrada":"",
    "qt_horasEstagio":"",
    "ic_check":""
}

###

DELETE http://localhost:3333/estagiario/