POST http://localhost:3333/empresa
Content-Type: application/json

{
    "nm_empresa": ""
}

###

GET http://localhost:3333/empresa?search=

###

PUT http://localhost:3333/empresa/
Content-Type: application/json

{
    "nm_empresa": ""
}

###

DELETE http://localhost:3333/empresa/