POST https://student-register-bnaf.onrender.com/create
Content-type: application/json

{
    "nm_login":"",
    "cd_senha":"",
    "cd_curso": ""
}

###

POST https://student-register-bnaf.onrender.com/login
Content-type: application/json

{
    "nm_login": "",
    "cd_senha": ""
}

###

POST https://student-register-bnaf.onrender.com/sessionCheck
Content-Type: application/json

{
    "token": ""
}

###

GET https://student-register-bnaf.onrender.com/loginList?search=&curso=

###

PUT https://student-register-bnaf.onrender.com/logoff/

###

PUT https://student-register-bnaf.onrender.com/login/
Content-type: application/json

{
    "nm_login":""
}

###

DELETE https://student-register-bnaf.onrender.com/login/