POST https://student-register-bnaf.onrender.com/curso
Content-Type: application/json

{
    "nm_curso": ""
}

###

GET https://student-register-bnaf.onrender.com/curso?search=

###

PUT https://student-register-bnaf.onrender.com/curso/300f1b28-a6ef-42a6-acf9-bea7dcabe3b6
Content-Type: application/json

{
    "nm_curso": ""
}

###

DELETE https://student-register-bnaf.onrender.com/curso/858cfd10-16fa-45a0-b23b-59534450f7e2