POST http://localhost:3333/create
Content-type: application/json

{
    "nm_login":"Teste2",
    "cd_senha":"123",
    "cd_curso": "6fed0262-4b27-42d9-988f-1a1a5c80570d"
}

###

POST http://localhost:3333/login
Content-type: application/json

{
    "nm_login": "Teste",
    "cd_senha": "123"
}

###

POST http://localhost:3333/sessionCheck
Content-Type: application/json

{
    "token": "aee1f7fc-e8dc-4dab-a939-85ae64f002b9"
}

###

GET http://localhost:3333/loginList?search=&curso=

###

PUT http://localhost:3333/logoff/

###

PUT http://localhost:3333/login/f3419821-c710-4b7a-9788-eadbb55dda94
Content-type: application/json

{
    "nm_login":"Yesus"
}

###

DELETE http://localhost:3333/login/a60c1884-c41e-4cf0-ab60-7964c03fc9b0