POST http://localhost:3333/ciclo
Content-Type: application/json

{
    "cd_curso": "",
    "nm_ciclo": ""
}

###

GET http://localhost:3333/ciclo?search=&curso=

###

PUT http://localhost:3333/ciclo/
Content-Type: application/json

{
    "cd_curso": "",
    "nm_ciclo": ""
}

###

DELETE http://localhost:3333/ciclo/