POST http://localhost:3333/curso
Content-Type: application/json

{
    "nm_curso": ""
}

###

GET http://localhost:3333/curso?search=

###

PUT http://localhost:3333/curso/
Content-Type: application/json

{
    "nm_curso": ""
}

###

DELETE http://localhost:3333/curso/