POST https://student-register-bnaf.onrender.com/estagiario
Content-Type: application/json

{
    "cd_curso": "", 
    "cd_registroMatricula": "", 
    "dt_periodoComeco": "", 
    "dt_periodoTermino": "", 
    "nm_empresa": "", 
    "nm_estagiario": ""
}

###

GET https://student-register-bnaf.onrender.com/estagiario?search=&empresa=&RA=&curso=

###

PUT https://student-register-bnaf.onrender.com/estagiario/adasdasdasda12312312312
Content-Type: application/json

{
    "cd_curso": "", 
    "dt_periodoComeco": "", 
    "dt_periodoTermino": "", 
    "nm_empresa": "", 
    "nm_estagiario": ""
}

###

DELETE https://student-register-bnaf.onrender.com/estagiario/a