POST http://localhost:3333/create
Content-type: application/json

{
    "nm_login":"Work",
    "cd_senha":"123"
}

###

POST http://localhost:3333/login
Content-type: application/json

{
    "nm_login": "work",
    "cd_senha": "123"
}

###

GET http://localhost:3333/sessionCheck
token: 19077957-44c4-4824-80ad-d9a6509345e5

###

GET http://localhost:3333/loginList

###

PUT http://localhost:3333/login/
Content-type: application/json

{
    "nm_login":""
}

###

DELETE http://localhost:3333/login/