POST http://localhost:3333/login
Content-type: application/json

{
    "nm_login":"",
    "cd_senha":""
}

###

GET http://localhost:3333/login

###

PUT http://localhost:3333/login/
Content-type: application/json

{
    "nm_login":""
}

###

DELETE http://localhost:3333/login/